-- AlterTable
ALTER TABLE "Profile" ADD COLUMN     "companySizePreference" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "companyTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "degrees" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "education" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "excludePublishers" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "industries" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "locationRadius" INTEGER,
ADD COLUMN     "maxSalary" INTEGER,
ADD COLUMN     "minSalary" INTEGER,
ADD COLUMN     "primarySkills" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "recommendedDatePosted" TEXT NOT NULL DEFAULT 'week',
ADD COLUMN     "recommendedNumPages" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "roleTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "searchNumPages" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "secondarySkills" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "seniority" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "timezonePreference" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "workModePreference" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "yearsOfExperience" INTEGER;
